version: '3'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    networks:
      - poll-tier
      - back-tier
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=polls
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - back-tier
      - result-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=polls
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - back-tier
    depends_on:
      - db
      - redis
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=polls
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - result-tier
    restart: always

networks:
  poll-tier:
  back-tier:
  result-tier:

volumes:
  db-data:
